#debug: true
server:
  port: 6789
spring:
  jackson:
    generator:
      write-numbers-as-strings: false
  datasource:
    url: 'jdbc:mariadb://smartcity.itlife.com.tw:16033/estate?useUnicode=true&sessionVariables=character_set_connection=utf8mb4,character_set_client=utf8mb4&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true'
    driver-class-name: 'org.mariadb.jdbc.Driver'
    username: 'smartcity'
    password: 'fPEkJYkJ1torjbRWRb0mpx1o29kaXpJd'
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000 # 30秒
      validation-timeout: 5000 # 5秒
      idle-timeout: 300000  # 5分鐘
      max-lifetime: 600000  # 10分鐘, 必須要比wait_timeout小
      keepalive-time: 120000 # 2分鐘
      leak-detection-threshold: 60000 # 60秒，幫助找出連線洩漏
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 800
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    hibernate:
      dll-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  graphql:
    jpa:
      enabled: true
      # path: /api/graphql
dsg:
  graphql:
    virtualthreads:
      enabled: true
    graphiql:
      enabled: true
      #path: /graphiql   # 瀏覽器打開 http://localhost:6789/graphiql
logging:
  level:
    org.hibernate.SQL: DEBUG
#    me.ahoo.cosid: debug

cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    instance-id: ${spring.application.name}:${random.long[1000,99999]}   # 確保唯一
    distributor:
      type: manual
      manual:
        machine-id: 0 # 手動分配的機器 ID，單機部署固定設為 0 即可
  snowflake:
    enabled: true # 啟用雪花算法 ID 生成器
    share:
      clock-sync: true # 啟用時鐘回撥自動同步等待（強烈建議開啟，防止伺服器時鐘回撥導致報錯）